### ISSUE TITLE
Reset-Counters

### ISSUE THREAD

**Issue by RaelKbg** [janmohammadi/MikrotikDotNet#1]
Hi 

I'm putting a tool in place that will assist with resetting users download used from the user-manager. However I'm unable to execute this command with this api: /tool user-manager user reset-counters numbers=1

can you please assist?

thanks
Rael

**Comment by janmohammadi** [comment]
Hi
You everytime you need to point to a Number in API.
You must print that first to get the ID
And then set ID as command argument
