### ISSUE TITLE
how remove pppoe active user?

### ISSUE THREAD

**Issue by danielolinto** [janmohammadi/MikrotikDotNet#10]
I need to lease this command: /ppp/active/remove  using .id parameter. How can i do this?

**Comment by janmohammadi** [comment]
@mohsenghodrat

**Comment by mohsenghodrat** [comment]
Hi daniel
what do you want to do?
by this code /ppp/active/remove numbeers=id    you can kill (kick)  user for a couple of seconds,
if you want to remove a user, at first you must find the user id then remove it user, by id:
for find users and id :
 
using (var conn = new MKConnection("192.168.1.5", "admin", "123456", 8291))
            {
                conn.Open();
                var cmd = conn.CreateCommand("ppp secret print");
                cmd.Parameters.Add("where", "name");
                var result = cmd.ExecuteReader();
                foreach (var line in result)
                {
                    //get list of users and id in /ppp/secret
                    var raw = MikrotikDotNet.ReponseParser.RowParser.Parse(line);
                    //print user id
                    Console.WriteLine(raw[".id"]);
                    //Get user id
                    //var id = raw[".id"].Substring(1);
                }
            }
for remove user :

 using (var conn = new MKConnection("192.168.1.5", "admin", "123456", 8291))
            {
                conn.Open();
                 cmd = conn.CreateCommand("ppp secret remove");
                cmd.Parameters.Add("numbers", id.toString());
                cmd.ExecuteNonQuery();
            }
----------------------------------------------------------------------
simple code:

using (var conn = new MKConnection("192.168.1.5", "admin", "123456", 8291))
            {
                conn.Open();
                var cmd = conn.CreateCommand("ppp secret print");
                cmd.Parameters.Add("where", "name");
                var result = cmd.ExecuteReader();
                foreach (var line in result)
                {
                    //get list of users and id in /ppp/secret
                    var raw = MikrotikDotNet.ReponseParser.RowParser.Parse(line);
                    //Get user id
                    var id = raw[".id"].Substring(1);
                   //remove user by id
                    cmd = conn.CreateCommand("ppp secret remove");
                    cmd.Parameters.Add("numbers", id.ToString());
                    cmd.ExecuteNonQuery();
                }
            }

**Comment by danielolinto** [comment]
Thanks a lot!
