### ISSUE TITLE
Char minus in property name

### ISSUE THREAD

**Issue by alkar1** [janmohammadi/MikrotikDotNet#13]
Hi, I can't do:

`
class MyVlan

    {
        public string MKID { get; set; } 
        public short vlan-ids { get; set; } //compile error
    }
`

I suggest replace underscore to minus (vlan_ids) and change code: 

`       

 public static string PascalToTrain(string name)

        {
            if (name.ToLower() == "mkid")
                return ".id";
            var n = name.Replace('_', '-');
            //return Regex.Replace(name, "(\\B[A-Z])", "-$1").ToLower();
            return Regex.Replace(n, "(\\B[A-Z])", "-$1").ToLower();
        }
`

**Comment by janmohammadi** [comment]
Hi @alkar1,
Sorry for my late reply!
I really can't get your point,
You can't define a variable with dash in C#, You can name it VlanIds and it has to work properly.

**Comment by alkar1** [comment]
Hi, 
Sorry my mistake, I didn't know there was a programmatic conversion of VlanIds to vlan-ids.
