### ISSUE TITLE
Filter result

### ISSUE THREAD

**Issue by tiransa** [janmohammadi/MikrotikDotNet#2]
i use tool user-manager user print command and try to filter required fields. how can i pass words likes shared-users

`class MyIpAddress
{
    public string username { get; set; }  //MKID always referce to .id field in response.
    public string password { get; set; } // Use PascalCase naming style for properties. it will convert from/to kebab-case naming.
    public string shared-users { get; set; }
}
//------------------------------------------------
using (var conn = new MKConnection(IPADDRESS, USERNAME, PASSWORD))
{
    conn.Open();
    var cmd = conn.CreateCommand("tool user-manager user print");
    var result = cmd.ExecuteReader<MyIpAddress>();

    foreach (var ip in result)
        Console.WriteLine($"{ip.username} - {ip.password} - {ip.shared-users}");

}`

**Comment by janmohammadi** [comment]
Hi

First of all
please note that is naming convention in C# is PascalCase for properties.
so you should define your model as blow:
mikrotik.net will convert PascalCase to kebab-case for you.
(example SharedUsers will pass to router as shared-users)
```cs
class MyIpAddress
{
    public string Username { get; set; } 
    public string Password { get; set; }
    public string SharedUsers { get; set; }
}
```
Then use ExecuteReader<MyIpAddress> method to read the results.

```cs
using (var conn = new MKConnection(IPADDRESS, USERNAME, PASSWORD))
{
    conn.Open();
    var cmd = conn.CreateCommand("tool user-manager user print");
    var result = cmd.ExecuteReader<MyIpAddress>();
    foreach (var user in result)
        Console.WriteLine($"{user.Username} - {user.Password} - {user.SharedUsers}");
}
```

**Comment by tiransa** [comment]
thank you dear
