### ISSUE TITLE
how to get suggestion mikrotik key words?

### ISSUE THREAD

**Issue by bi9595** [janmohammadi/MikrotikDotNet#7]
Hi dear professor,
please help me about:
how to get all suggestions mikrotik key words from the beginning and after every command,
when i press "?" or "tab" ?

Regards

**Comment by janmohammadi** [comment]
I'm afraid it's not possible through API. Maybe it's better to try SSL or Telenet protocol.
What's the purpose of that? Do you want to create something like Terminal?

**Comment by bi9595** [comment]
> I'm afraid it's not possible through API. Maybe it's better to try SSL or Telenet protocol.
> What's the purpose of that? Do you want to create something like Terminal?

Yes almost. I'm implementing a program to manage the processes of some routers that I needed for this feature.
Thank you for your time.
