### ISSUE TITLE
How to use filter "find" in set command ?

### ISSUE THREAD

**Issue by bi9595** [janmohammadi/MikrotikDotNet#8]
Hi,
please help me about:
how to get use filter "find" without using ".id"  in set command ?
for exmple: 
1- interface set [ find name=ether1 ] comment=abcd
2- interface set ether1 comment=34343434

Is possible above commands in MikrotikDotNet?

Regards

**Comment by janmohammadi** [comment]
You have to find them first and iterate through IDs and run the set command and pass the MKID.
Please note that it's not related to MikrotikDotNet. It's how Mikrotik API protocol works.
Something like this: (I did not test this code)
```cs
var interfaces=conn.CreateCommand("interface print where name=ether1").ExecuteReaderDynamic();
for(var i in interfaces){
     var cmd=conn.CreateCommand("interface set");
     cmd.Parameters.Add(".Id", i.MKID);
     cmd.Parameters.Add("Comment", "abcd");
     cmd.ExecuteNonQuery();
}


```
